### ISSUE TITLE
Bing keeps saying IP banned

### ISSUE THREAD

**Issue by james-elicx** [syrex1013/RainbowSQL#2]
Bing keeps returning IP banned despite saying you don't need proxies. It works fine when I go into my web browser and search. I've tried my home IP and several VPN servers but I still get this issue.

**Comment by syrex1013** [comment]
Hi,
I will look into it.

**Comment by syrex1013** [comment]
Please do this:
1.Run RainbowSQL until you get "IP Banned" error. Dont use any proxies.
2.Try to search **DORK YOU LOADED IN TXT FILE** normally in bing.com. See if you get any results.

Please report back if you got results and what dork have you used.

**Comment by james-elicx** [comment]
> Please do this:
> 1.Run RainbowSQL until you get "IP Banned" error. Dont use any proxies.
> 2.Try to search **DORK YOU LOADED IN TXT FILE** normally in bing.com. See if you get any results.
> 
> Please report back if you got results and what dork have you used.

Just tried with the basic dork `inurl:".php?id=1"` and got IP banned yet when I searched it manually after getting the IP banned message I got results.

**Comment by syrex1013** [comment]
OK, issue should be fixed in the upcoming update.
